### ISSUE TITLE
Under-segmented for 128-beam LiDAR?

### ISSUE THREAD

**Issue by WSTao** [wangx1996/Fast-Ground-Segmentation-Based-on-JPC#1]
![10](https://user-images.githubusercontent.com/30944722/136647960-1d7209d3-3255-4a30-9d6c-6178bdad4514.png)

![12](https://user-images.githubusercontent.com/30944722/136647964-61d50aeb-009d-4c98-a38c-adc546bb1118.png)

When I test with 128-beam data, the ground will be under-segmented，how to modify those parameters?
thanks much！

**Comment by wangx1996** [comment]
@WSTao You may change the range image resolution based on your lidar type.

**Comment by WSTao** [comment]
> @WSTao You may change the range image resolution based on your lidar type.

Yes, I modified it, but there are still under-segmentation, especially at the edge of occlusion.

**Comment by wangx1996** [comment]
@WSTao  Maybe you can change the other parameters, or check the algorithm that I  implemented is right or wrong.

**Comment by WSTao** [comment]
I will try, thank you
