### ISSUE TITLE
关于点云数据格式

### ISSUE THREAD

**Issue by YaleMeng** [wangx1996/Fast-Ground-Segmentation-Based-on-JPC#2]
谢谢你的项目分享，想问一下full_cloud2.pcd中的ring字段的数值是怎么得到的？谢谢！

**Comment by wangx1996** [comment]
@YaleMeng  对于KITTI数据集用这个：
https://github.com/wangx1996/Fast-Ground-Segmentation-Based-on-JPC/blob/0b4dc317db79197078e78a741b499c5042cdb7df/jpc_seg/src/kitti_file_main.cpp#L165

**Comment by YaleMeng** [comment]
@wangx1996 非常感谢。如果是自己的实测数据，是不是也可以按照add_ring_info（）来计算ring？
还有一点：class JpcGroundRemove中的width，height是根据LiDAR的参数计算的吗？2083这个数好奇怪。
谢谢！

**Comment by wangx1996** [comment]
@YaleMeng 这是根据一些常用的将kitti投成深度图的方法选择的分辨率，add_ring 也只适用kitti数据，你自己有雷达可以自己去算他的图像分辨率并且可以直接得到ring

**Comment by YaleMeng** [comment]
@wangx1996 好的，非常感谢。我再看一下论文、理解一下。
