### ISSUE TITLE
没有把点云中所有的点都分类，有部分剩余

### ISSUE THREAD

**Issue by liuzhenboo** [wangx1996/Fast-Ground-Segmentation-Based-on-JPC#3]
没有把点云中所有的点都分类，有部分剩余

cpp文件的for循环：

![1](https://user-images.githubusercontent.com/57830284/144599243-9d0bb351-ab6d-435a-8297-d18c23e1cda9.png)

实验测试，其中红色为地面，绿色为障碍物，蓝色未确定

![2](https://user-images.githubusercontent.com/57830284/144599675-a70e6fba-17f2-4b6f-bb8f-51d3dcfaa5aa.png)

项目里面的gif动图里面也有部分黑点．

**Comment by wangx1996** [comment]
@liuzhenboo 1.选定了距离范围 2.投影成深度图有损失
